project/aplicatie1/urls.py
from django.urls import path

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

project/jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('', views.JobsView.as_view(), name='lista_jobs'),
    path('adaugare/', views.CreateJobsView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateJobsView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_jobs, name='dezactiveaza'),
    path('<int:pk>/activeaza/', views.activate_jobs, name='activeaza'),
]

project/myapi/urls.py
from django.urls import path, include
from rest_framework import routers

from myapi import views

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))
]

project/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path('jobs/', include('jobs.urls')),
    path('profile/', include('user_profile.urls')),
    path('api/', include('myapi.urls'))
]

project/user_profile/urls.py
from django.urls import path

from user_profile import views

app_name = 'userprofile'

urlpatterns = [
    path('start_timesheet/', views.new_timesheet, name='start_pontaj'),
    path('stop_timesheet/', views.stop_timesheet, name='stop_pontaj'),
]

project/aplicatie1/models.py
from django.db import models


class Locations(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=150)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.city} - {self.country}"

project/jobs/models.py
from django.db import models


class Jobs(models.Model):

    type = models.CharField(max_length=11,)
    url = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=150)
    how_to_apply = models.TextField(max_length=150)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.type} - {self.title} - {self.url}"

project/myapi/models.py
from django.db import models

# Create your models here.

project/user_profile/models.py
from django.db import models


class Logs(models.Model):

    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10)
    url = models.CharField(max_length=100)


class Pontaj(models.Model):

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True)

project/aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie1.models import Locations


class LocationsView(LoginRequiredMixin, ListView):
    model = Locations
    template_name = 'aplicatie1/locations_index.html'
    paginate_by = 5


class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


@login_required
def delete_location(request, pk):
    Locations.objects.filter(id=pk).update(active=0)
    return redirect('locations:lista_locatii')


@login_required
def activate_location(request, pk):
    Locations.objects.filter(id=pk).update(active=1)
    return redirect('locations:lista_locatii')

project/aplicatie2/views.py
from django.shortcuts import render

# Create your views here.

project/jobs/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from jobs.models import Jobs


class JobsView(LoginRequiredMixin, ListView):
    model = Jobs
    template_name = 'jobs/jobs_index.html'


class CreateJobsView(LoginRequiredMixin, CreateView):
    model = Jobs
    fields = ['type', 'url', 'title', 'description', 'how_to_apply']
    template_name = 'jobs/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:lista_jobs')


class UpdateJobsView(LoginRequiredMixin, UpdateView):
    model = Jobs
    fields = ['type', 'url', 'title', 'description', 'how_to_apply']
    template_name = 'jobs/jobs_form.html'

    def get_success_url(self):
        return reverse('jobs:lista_jobs')


@login_required
def delete_jobs(request, pk):
    Jobs.objects.filter(id=pk).update(active=0)
    return redirect('jobs:lista_jobs')


@login_required
def activate_jobs(request, pk):
    Jobs.objects.filter(id=pk).update(active=1)
    return redirect('jobs:lista_jobs')

project/myapi/views.py
from rest_framework import viewsets

from aplicatie1.models import Locations
from myapi.serializers import LocationSerializers


class LocationViewSet(viewsets.ModelViewSet):
    queryset = Locations.objects.all().order_by('city')
    serializer_class = LocationSerializers

project/user_profile/views.py
import datetime
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from user_profile.models import Pontaj


@login_required
def new_timesheet(request):
    Pontaj.objects.create(user_id=request.user.id, start_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def stop_timesheet(request):
    Pontaj.objects.filter(user_id=request.user.id, end_date=None).update(end_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

project/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

project/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'locations:adauga' %}" class="btn btn-success">Adauga locatie</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>City</th>
            <th>Country</th>
            <th>Stare</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for item in locations_list %}
            <tr>
                <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                <td>{{ item.city }}</td>
                <td>{{ item.country }}</td>
                <td>{% if item.active == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>
                <td>
                    <a href="{% url 'locations:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'locations:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'locations:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="d-flex align-items-center">
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
                {% else %}
                    <li class="disabled btn"><span><<</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
                    {% else %}
                        <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
                {% else %}
                    <li class="disabled btn"><span>>></span></li>
                {% endif %}
                <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
            {{ page_obj.paginator.count }}
        </span>
            </ul>
        {% endif %}
    </div>
{% endblock %}

project/templates/base.html
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                {% if request.user.is_authenticated %}
                    <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                    <a class="btn" href="{% url 'jobs:lista_jobs' %}">Jobs</a>
                    <a class="btn" href="{% url 'logout' %}">Logout</a>
                    <span>Hi, {{ request.user.username|upper }}</span>
                    {% if ready_to_work is False %}
                        <a href="{% url 'userprofile:stop_pontaj' %}" class="btn btn-danger">Oprire pontaj</a>
                    {% else %}
                        <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Pornire pontaj</a>
                    {% endif %}
                {% endif %}
            </nav>
        </div>
    </div>
</div>
<div class="col-md-12">
    {% block content %}
    {% endblock %}
</div>
</body>

</html>

project/templates/jobs/jobs_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label }} {{ field }}<br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

project/templates/jobs/jobs_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'jobs:adauga' %}" class="btn btn-success">Adauga job</a>
    <br>
    <table class="table">
        <thead>
        <tr>
            <th>Index</th>
            <th>Type</th>
            <th>Url</th>
            <th>Title</th>
            <th>Description</th>
            <th>How to apply</th>
        </tr>
        </thead>
        <tbody>
        {% for item in jobs_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.type }}</td>
                <td>{{ item.url }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.how_to_apply }}</td>
                <td>{% if item.active == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>
                <td>
                        <a href="{% url 'jobs:modifica' item.id %}" class="btn btn-success">Modifica</a>
                    {% if item.active == 1 %}
                        <a href="{% url 'jobs:dezactiveaza' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                        <a href="{% url 'jobs:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}